### ISSUE TITLE
Category based Downloads

### ISSUE THREAD

**Issue by Basilakis** [aristath/edd-remote-installer#2]
Hey,

can I add to ?edd_action=get_downloads a specific category of downloads to pull & not all the downloads from the site?

Is that possible?

Thank you!

**Comment by thefrosty** [comment]
@Basilakis It's something I plan on including in my forked copy. I imaging that it it would be a welcomed feature and merged in.

**Comment by aristath** [comment]
Archiving this repository and moving things to new repos (links in the readme file) so I'll go ahead and close this one.
The new versions will be completely rebuilt from scratch so any and all issues that existed will be resolved when I'm finished with them.
