### ISSUE TITLE
Double firing of AJAX

### ISSUE THREAD

**Issue by thefrosty** [aristath/edd-remote-installer#5]
When submitting a license request the is returned the first time multiple requests could happen.

This also could happen if you click the install button then exit the thickbox modal and click install on a separate download. Thinking an AJAX modal is needed or generated inline of each download.

**Comment by aristath** [comment]
What if we did something like this:

```php
// set our transient name here
$transient_name = 'my_updater_running_tasks';
// Get any current tasks.
// returns false if none are set.
$current_tasks = get_transient( $transient_name );
$current_tasks = ( false === $current_tasks ) ? array() : $current_tasks;
// This is the task we want to add.
// $id is the product-if for example
// $args are whatever we need.
$new_task = array(
    $id => $args,
);
// merge the arrays
$tasks = wp_parse_args( $new_task, $current_tasks );
// update transient if needed
if ( $current_tasks != $tasks ) {
	set_transient( $transient_name, $tasks, 600 );
}
```

Then we can check the value of the transient and no duplicate tasks will be contained there... no matter what users do

**Comment by aristath** [comment]
So basically, create a queue of requests in a transient and process them using that as reference.
It doesn't have to be a transient... we can use options too, as long as we delete it when the process is done to avoid filling up the `wp_options` table with trash

**Comment by thefrosty** [comment]
Interesting idea. I'll play around with this the next few days while I am at Pressnomics.

**Comment by aristath** [comment]
Archiving this repository and moving things to new repos (links in the readme file) so I'll go ahead and close this one.
The new versions will be completely rebuilt from scratch so any and all issues that existed will be resolved when I'm finished with them.
